 var x = Math.floor((Math.random() * 50)); 

 	localStorage.setItem(0,"The true measure of a man is how he treats someone who can do him absolutely no good.");
	localStorage.setItem(1,"I don’t count my sit-ups. I only start counting when it starts hurting. That is when I start counting, because then it really counts. That’s what makes you a champion.");
	localStorage.setItem(2,"A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing.");
	localStorage.setItem(3,"If you can’t explain it simply, you don’t understand it well enough");
	localStorage.setItem(4,"The reasonable man adapts himself to the world; the unreasonable one persists in trying to adapt the world to himself. Therefore all progress depends on the unreasonable man.");
	localStorage.setItem(5,"There isn’t anything noble about being superior to another person. True nobility is in being superior to the person you once were.");
	localStorage.setItem(6,"Every saint has a past and every sinner has a future.");
	localStorage.setItem(7,"The things you do for yourself are gone when you are gone, but the things you do for others remain as your legacy.");
	localStorage.setItem(8,"[Man] sacrifices his health in order to make money. Then he sacrifices money to recuperate his health. And then he is so anxious about the future that he does not enjoy the present; the result being that he does not live in the present or the future; he lives as if he is never going to die, and then dies having never really lived.");
	localStorage.setItem(9,"I am the wisest man alive, for I know one thing, and that is that I know nothing.");
	localStorage.setItem(10,"Whether you think you can, or you think you can’t — either way you’re right.");
	localStorage.setItem(11,"People who take the sun-lit world of the senses to be good and real are living pitifully in a den of evil and ignorance.");
	localStorage.setItem(12,"He who asks a question remains a fool for five minutes. He who does not ask remains a fool forever.");
	localStorage.setItem(13,"Books can be dangerous. The best ones should be labeled “This could change your life.");
	localStorage.setItem(14,"At school, new ideas are thrust at you every day. Out in the world, you’ll have to find your inner motivation to seek for new ideas on your own.");
	localStorage.setItem(15,"Every gun that is made, every warship launched, every rocket fired, signifies in the final sense a theft from those who hunger and are not fed, those who are cold and are not clothed.");
	localStorage.setItem(16,"A society grows great when old men plant trees whose shade they know they shall never sit in.");
	localStorage.setItem(17,"Most people do not listen with the intent to understand. Most people listen with the intent to reply.");
	localStorage.setItem(18,"If you want to make God laugh, tell him about your plans.");
	localStorage.setItem(19,"Even a clock that does not work is right twice a day.");
	localStorage.setItem(20,"Every villain is a hero in his own mind.");
	localStorage.setItem(21,"If an egg is broken by an outside force, life ends. If broken by an inside force, life begins. Great things always begin from the inside.");
	localStorage.setItem(22,"The reason why we struggle with insecurity is because we compare our behind the scenes with everyone else’s highlight reel.");
	localStorage.setItem(23,"The greatest danger for most of us is not that our aim is too high and we miss it but that it is too low and we reach it");
	localStorage.setItem(24,"Too many people buy things they don’t need with money they don’t have to impress people they don’t like.");
	localStorage.setItem(25,"I freed 1000 slaves. I could have freed 1000 more if only they knew they were slaves.");
	localStorage.setItem(26,"And the only way to do great work is to love what you do. If you haven’t found it yet, keep looking. Don’t settle. As with all matters of the heart, you’ll know when you find it.");
	localStorage.setItem(27,"No matter how many mistakes you make or how slow you progress, you are still way ahead of everyone who isn’t trying.");
	localStorage.setItem(28,"No snowflake in an avalanche ever feels responsible.");
	localStorage.setItem(29,"Have I not destroyed my enemy when I have made him into my friend?");
	localStorage.setItem(30,"You don’t drown by falling in the water. You drown by staying there.");
	localStorage.setItem(31,"I don’t understand why when we destroy something created by man we call it vandalism, but when we destroy something created by nature we call it progress.");
	localStorage.setItem(32,"Thousands of candles can be lighted from a single candle, and the life of the candle will not be shortened. Happiness never decreases by being shared.");
	localStorage.setItem(33,"Prejudices are rarely overcome by argument; not being founded in reason they cannot be destroyed by logic.");
	localStorage.setItem(34,"Many are stubborn in pursuit of the path they have chosen, few in pursuit of the goal.");
	localStorage.setItem(35,"A ship is safe in harbor, but that’s not what ships are for.");
	localStorage.setItem(36,"Life isn’t about finding yourself. Life is about creating yourself.");
	localStorage.setItem(37,"Never interfere with your enemy when he is making a mistake.");
	localStorage.setItem(38,"Happiness is not determined by what’s happening around you, but rather what’s happening inside you. Most people depend on others to gain happiness, but the truth is, it always comes from within.");
	localStorage.setItem(39,"Forgive others, not because they deserve forgiveness, but because you deserve peace.");
	localStorage.setItem(40,"Sometimes I think we’re alone in the universe, and sometimes I think we’re not. In either case, the idea is quite staggering.");
	localStorage.setItem(41,"If you want to build a ship, don’t drum up the men to gather wood, divide the work and give orders. Instead, teach them to yearn for the vast and endless sea.");
	localStorage.setItem(42,"I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.");
	localStorage.setItem(43,"The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.");
	localStorage.setItem(44,"Do the difficult things while they are easy and do the great things while they are small. A journey of a thousand miles must begin with a single step.");
	localStorage.setItem(45,"Life is 10% of what happens to you and 90% of how you react to it.");
	localStorage.setItem(46,"One original thought is worth a thousand mindless quotings.");
	localStorage.setItem(47,"If you don’t like something, change it. If you can’t change it, change the way you think about it.");
	localStorage.setItem(48,"We are a way for the cosmos to know itself.");
	localStorage.setItem(49,"A witty saying proves nothing.");
	localStorage.setItem(50,"Even the finest sword plunged into salt water will eventually rust.");

	var Q = document.getElementById('mot-quote');
	var y = localStorage.getItem(x);
	Q.innerHTML = y;
